### ISSUE TITLE
NULL pointer exceptions on "cave" when changing level

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#872] opened 2013-11-19 22:10 UTC
Issue raised by powerwyrm

This is a vast problem that could cause a lot of server crashes in rare circumstances. This ticket will be here to fix them.

Here's an explanation of the problem. The commands sent by the client are processed in process_pending_commands(), which is called at the beginning of process_player_end() in the main loop function dungeon(). When a player changes level, his dun_depth variable is updated and his new_level_flag is set to TRUE. At this time, the old dungeon level cave[old_depth] is still allocated, while the new dungeon level cave[dun_depth] may be unallocated (if there was nobody on that level and it was not static). '''If this is the case, every call to cave[dun_depth] in the code will crash the server with a NULL pointer exception.''' Only much later in the main loop function dungeon() is the old dungeon level cave[old_depth] deallocated and the new dungeon level cave[dun_depth] allocated.

Here's a good example of the problem: in process_player_begin(), which is called after the player's depth has been updated, there's the check for random teleportation which calls teleport_player(), a function that uses cave[dun_depth]... if a player changes level and in the same turn the random teleportation kicks in, the server crashes due to trying to teleport a player on an unallocated level...

A simple fix would be to "freeze" the player between the time depth changes (new_level_flag = TRUE) and the time the level is actually allocated (new_level_flag = FALSE), and just process the world during that time without that player.

**Comment by flambard-took** [comment] 2019-08-18 19:56
I believe the 'freezing' solution provided by PowerWyrm works great, we never had a crash like that, in neither 1.1-1.4, neither 1.5+ versions.

There are probably some edge cases, in the *opposite* direction, i.e. we *need* to process player, but we don't. Alas, we can create new tickets if anything like that is discovered.

**Comment by flambard-took** [comment] 2019-08-20 19:27
Funnily enough, this bug hasn't manifested for like 6 years, but as soon as I close this ticket, **wham**, server crashes galore. Oh well.

**Closed** 2019-08-20 19:36 UTC
Labels: bug, high

**Comment by billsey** [comment] 2019-08-20 22:07
Obviously, you fixed whatever was hiding it. Now you can fix the cause instead of the hiding.

Bill

Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by flambard-took** [comment] 2019-08-21 06:24
@billsey, the latest crash went like this:

- player has low hp (and is displayed as symbol `6`)
- player changes level
- the cave structure for the new level is not *yet* allocated
- regen kicks in
- his hp goes back to max
- his symbol goes from `6` to `@`
- we try to send visual update for that
- to do this we need to query map_info, to get terrain, light, etc
- but the cave structure is still not allocated!
- CRASH

It *looked* like this can't happen, because we escape early out of `process_player_end`, which handles regen, but if we examine it more carefully, dungeon level switch can happen as a result of `>` or `<` player command, and those are processed *after* we do our Paranoia check. So, a bit clumsily, we now test both at the start of process_player_end and right after we flush pending commands, few lines of code later.

Hopefully, this is the last time something like that happens.
