### ISSUE TITLE
turn off auto-kick on fainting

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1325] opened 2019-08-14 21:49 UTC
Today I've drinked potion and was kicked from the game

When I relogged I saw that char is starving, so it seems it was salt water potion.

Please could you add option not to kick player on starving, like Powerwyrm added recently:
http://angband.oook.cz/forum/showthread.php?p=135707&highlight=starving+kick#post135707

**Comment by flambard-took** [comment] 2019-08-15 01:07
Duplicate of #1156.

**Closed by flambard-took** 2019-08-15 01:07 UTC
Labels: duplicate

**Comment by igroglaz** [comment] 2019-08-15 07:40
Actually it's not duplicate, as it's vice versa issue. I saw that topic before I've created this one

**Comment by flambard-took** [comment] 2019-08-15 14:14
You are somewhat right, but #1156 is actually another symptom of the same problem (auto-kick being broken, in multiple ways).
