### ISSUE TITLE
Windows installer (NSIS) is obsolete 

### ISSUE THREAD

**Issue by grking** [mangband/mangband#1152] opened 2018-11-29 13:01 UTC
Is NSIS even maintained anymore? Not sure, Inno installer is, it supports Windows 10. Let's use that instead.

**Comment by billsey** [comment] 2018-12-06 23:31
Sorry, forgot to reopen...

**Comment by flambard-took** [comment] 2019-03-01 18:47
@billsey, are you sure about that? I've just tested those installers on fresh boxes, and they use
`C:\Users\<flambard>\AppData\Local\MAngband` on Win7+, and
`C:\Documents and Settings\<flambard>\Local Settings\Application Data\MAngband` on WinXP. Those locations are user-writable.

**Comment by billsey** [comment] 2019-03-01 20:36
The issue is that the AppData folder is hidden from the user. As you say it is writable but you have to manually type the name in or turn on Show Hidden Files in order to access it. Applications are expected to either store files in an appropriate library folder or provide an editor for data stored there.

Bill

Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by flambard-took** [comment] 2019-03-03 14:00
Ahh, that makes sense. I actually see a one quick work-around -- we can add a shortcut to the needed folder into the group that goes into Start Menu (the one that currently has 4 shortcuts - mangclient.exe, mangclient-sdl.exe, README-client.htm and "Uninstall"). It would ideally have a "folder + shortcut arrow" type of icon and could say something like "Open Config Dir".

For Documents solution, I've found this in Inno setup docs:
```
{userdocs} & {commondocs}

    The path to the My Documents folder.
```
Then, we can use its INI facilities to store correct LibDir in mangclient.ini

```
This optional section defines any .INI file entries you would like Setup to set on the user's system.

Here is an example of an [INI] section:

[INI]
Filename: "MyProg.ini"; Section: "InstallSettings"; Flags: uninsdeletesection
Filename: "MyProg.ini"; Section: "InstallSettings"; Key: "InstallPath"; String: "{app}"
```

Finally, we should edit the shortcut to include the -C flag with an approrpiate path TO the mangclient.ini file

```
[Icons] section
Parameters

    Optional command line parameters for the shortcut, which can include constants.
    Example:

    Parameters: "/play filename.mid"
```

This is a fairly complicated setup, but can be done.

**Comment by flambard-took** [comment] 2019-03-27 11:03
So I've added a "go to config dir" shortcut to the installer, that *should* alleviate @billsey's concerns in regards to "players would not be able to find the config dir, unless it's in Documents". I think this is much simpler than rewiring everything to use under-specified windows paths.

Secondly, since the title of the ticket says "NSIS is obsolete", I think the closing condition are met. If there are still concerns, please create a new ticket.

**Closed by flambard-took** 2019-03-27 11:03 UTC
Labels: bug
